name: Publish JAR file to GitHub Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and upload JAR
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: actions/checkout@v3
        run: mvn clean package

      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/jamabuild.jar
          prerelease: true
          overwrite: true