name: Publish JAR file to GitHub Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and upload JAR
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build
        run: mvn clean package

      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/jamabuild.jar
          prerelease: true
          overwrite: true